server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    charset utf-8;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Cache-Control "no-cache" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/velyric(-de|-en)?\.vcf$ {
        types { }
        default_type text/vcard;
        charset_types text/vcard;
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}
